# TODO(bison): Add schema.
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machineautoscalers.autoscaling.openshift.io
spec:
  group: autoscaling.openshift.io
  names:
    kind: MachineAutoscaler
    listKind: MachineAutoscalerList
    plural: machineautoscalers
    singular: machineautoscaler
  scope: Namespaced
  version: v1alpha1
