# TODO(bison): Add schema.
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterautoscalers.autoscaling.openshift.io
spec:
  group: autoscaling.openshift.io
  names:
    kind: ClusterAutoscaler
    listKind: ClusterAutoscalerList
    plural: clusterautoscalers
    singular: clusterautoscaler
  scope: Namespaced
  version: v1alpha1
