
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
  creationTimestamp: null
  name: machineautoscalers.autoscaling.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.scaleTargetRef.kind
    description: Kind of object scaled
    name: Ref Kind
    type: string
  - JSONPath: .spec.scaleTargetRef.name
    description: Name of object scaled
    name: Ref Name
    type: string
  - JSONPath: .spec.minReplicas
    description: Min number of replicas
    name: Min
    type: integer
  - JSONPath: .spec.maxReplicas
    description: Max number of replicas
    name: Max
    type: integer
  - JSONPath: .metadata.creationTimestamp
    description: MachineAutoscaler resoruce age
    name: Age
    type: date
  group: autoscaling.openshift.io
  names:
    kind: MachineAutoscaler
    listKind: MachineAutoscalerList
    plural: machineautoscalers
    shortNames:
    - ma
    singular: machineautoscaler
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MachineAutoscaler is the Schema for the machineautoscalers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification of constraints of a scalable resource
          properties:
            maxReplicas:
              description: MaxReplicas constrains the maximal number of replicas of
                a scalable resource
              format: int32
              minimum: 1
              type: integer
            minReplicas:
              description: MinReplicas constrains the minimal number of replicas of
                a scalable resource
              format: int32
              minimum: 0
              type: integer
            scaleTargetRef:
              description: ScaleTargetRef holds reference to a scalable resource
              properties:
                apiVersion:
                  description: 'APIVersion defines the versioned schema of this representation
                    of an object. Servers should convert recognized schemas to the
                    latest internal value, and may reject unrecognized values. More
                    info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources'
                  type: string
                kind:
                  description: 'Kind is a string value representing the REST resource
                    this object represents. Servers may infer this from the endpoint
                    the client submits requests to. Cannot be updated. In CamelCase.
                    More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds'
                  minLength: 1
                  type: string
                name:
                  description: Name specifies a name of an object, e.g. worker-us-east-1a.
                    Scalable resources are expected to exist under a single namespace.
                  minLength: 1
                  type: string
              required:
              - kind
              - name
              type: object
          required:
          - maxReplicas
          - minReplicas
          - scaleTargetRef
          type: object
        status:
          description: Most recently observed status of a scalable resource
          properties:
            lastTargetRef:
              description: LastTargetRef holds reference to the recently observed
                scalable resource
              properties:
                apiVersion:
                  description: 'APIVersion defines the versioned schema of this representation
                    of an object. Servers should convert recognized schemas to the
                    latest internal value, and may reject unrecognized values. More
                    info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources'
                  type: string
                kind:
                  description: 'Kind is a string value representing the REST resource
                    this object represents. Servers may infer this from the endpoint
                    the client submits requests to. Cannot be updated. In CamelCase.
                    More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds'
                  minLength: 1
                  type: string
                name:
                  description: Name specifies a name of an object, e.g. worker-us-east-1a.
                    Scalable resources are expected to exist under a single namespace.
                  minLength: 1
                  type: string
              required:
              - kind
              - name
              type: object
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
