apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: cluster-autoscaler-operator
  name: cluster-autoscaler-operator
  namespace: openshift-machine-api
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - openshift-machine-api
  selector:
    matchLabels:
      k8s-app: cluster-autoscaler-operator
